# Generated by Django 2.1.1 on 2018-09-12 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='phylum',
            name='phylum_name',
        ),
        migrations.AddField(
            model_name='animal',
            name='family',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='animals.Family'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='genus',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='animals.Genus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='animals.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='phylum',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='animals.Phylum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='animals.Species'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phylum',
            name='phylum',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='family',
            name='family_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='genus',
            name='genus_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='species',
            name='species_name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.AddField(
            model_name='animal',
            name='classa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='animals.ClassA'),
            preserve_default=False,
        ),
    ]
