# Generated by Django 2.1.1 on 2018-09-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20180912_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phylum',
            old_name='phylum',
            new_name='phylum_name',
        ),
    ]
